---
terraform_dir: "{{ playbook_dir }}/../terraform/"
terraform_instances_dir: "{{ terraform_dir }}/instances"
terraform_instance_dir: "{{ terraform_instances_dir }}/{{ terraform_instance_name }}"
terraform_instance_name: default
terraform_mode: plan
terraform_s3_remote_enabled: no
